  /* This file generated by /home/jmb/Documents/codes/bem_ax/install/atlas-3.10.2/bld/../src//tune/threads/probe_nthr.c */
#ifndef ATLAS_NTHREADS_H
   #define ATLAS_NTHREADS_H

#include "pthread.h"
   #define ATL_NTHREADS 8
   #define ATL_NTHRPOW2 3
   #ifdef ATL_LAUNCHORDER
       static int ATL_launchorder[8] = {0,4,2,6,1,5,3,7};
   #endif

#endif
