#ifndef ATL_INSTINFO_H
   #define ATL_INSTINFO_H

#define ATL_ARCH "Corei264AVX"
#define ATL_INSTFLAGS "-1 0 -a 1 -l 1"
#define ATL_F2CDEFS "-DAdd_ -DF77_INTEGER=int -DStringSunStyle"
#define ATL_ARCHDEFS "-DATL_OS_Linux -DATL_ARCH_Corei2 -DATL_CPUMHZ=3301 -DATL_AVX -DATL_SSE3 -DATL_SSE2 -DATL_SSE1 -DATL_USE64BITS -DATL_GAS_x8664"
#define ATL_DKCFLAGS "-fomit-frame-pointer -mfpmath=sse -O2 -fno-schedule-insns2 -mavx -m64"
#define ATL_DKC "/usr/bin/gcc-4.6"
#define ATL_SKCFLAGS "-fomit-frame-pointer -mfpmath=sse -O2 -fno-schedule-insns2 -mavx -m64"
#define ATL_SKC "/usr/bin/gcc-4.6"
#define ATL_DMCFLAGS "-fomit-frame-pointer -mfpmath=sse -O2 -fno-schedule-insns2 -mavx -m64"
#define ATL_DMC "/usr/bin/gcc-4.6"
#define ATL_SMCFLAGS "-fomit-frame-pointer -mfpmath=sse -O2 -fno-schedule-insns2 -mavx -m64"
#define ATL_SMC "/usr/bin/gcc-4.6"
#define ATL_ICCFLAGS "-DL2SIZE=4194304 -I/home/jmb/Codes/bem_ax/install/atlas-3.10.2/bld/include -I/home/jmb/Codes/bem_ax/install/atlas-3.10.2/bld/../src//include -I/home/jmb/Codes/bem_ax/install/atlas-3.10.2/bld/../src//include/contrib -DAdd_ -DF77_INTEGER=int -DStringSunStyle -DATL_OS_Linux -DATL_ARCH_Corei2 -DATL_CPUMHZ=3301 -DATL_AVX -DATL_SSE3 -DATL_SSE2 -DATL_SSE1 -DATL_USE64BITS -DATL_GAS_x8664 -m64 -DATL_FULL_LAPACK -DATL_NCPU=8 -fomit-frame-pointer -mfpmath=sse -O2 -fno-schedule-insns2 -mavx -m64"
#define ATL_ICC "/usr/bin/gcc-4.6"
#define ATL_F77FLAGS "-O -mavx -m64"
#define ATL_F77 "/usr/bin/x86_64-linux-gnu-gfortran"
#define ATL_DKCVERS "gcc-4.6 (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3"
#define ATL_SKCVERS "gcc-4.6 (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3"
#define ATL_DMCVERS "gcc-4.6 (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3"
#define ATL_SMCVERS "gcc-4.6 (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3"
#define ATL_ICCVERS "gcc-4.6 (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3"
#define ATL_F77VERS "GNU Fortran (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3"
#define ATL_SYSINFO "Linux gorge-hen 3.2.0-67-generic #101-Ubuntu SMP Tue Jul 15 17:46:11 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux"
#define ATL_DATE    "Wed Jun 24 16:06:09 PDT 2015"
#define ATL_UNAM    "jmb"
#define ATL_VERS    "3.10.2"

#endif
