#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
static void ATL_sJIK0x0x0TN1x1x6_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=0, 
 * lda=0, ldb=0, ldc=0, mu=1, nu=1, ku=6, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.2)
 */
{
   #define Mb M
   #define Nb N
   const int Kb = (K/6)*6;
   const float *stM = A + (lda*Mb);
   const float *stN = B + (ldb*Nb);
   #define incAk 6
   const int incAm = ((lda) - Kb), incAn = -(Mb*lda);
   #define incBk 6
   const int incBm = -(Kb), incBn = (ldb);
   #define incCm 1
   const int incCn = (ldc) - (Mb);
   float *pC0=C;
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0;
   register float rB0;
   register float rC0_0;
   do /* N-loop */
   {
      do /* M-loop */
      {
         rA0 = beta;
         rC0_0 = *pC0;
         rC0_0 *= rA0;
         for (k=0; k < Kb; k += 6) /* easy loop to unroll */
         {
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rC0_0 += rA0 * rB0;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rC0_0 += rA0 * rB0;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rC0_0 += rA0 * rB0;
            rA0 = pA0[4];
            rB0 = pB0[4];
            rC0_0 += rA0 * rB0;
            rA0 = pA0[5];
            rB0 = pB0[5];
            rC0_0 += rA0 * rB0;
            pA0 += incAk;
            pB0 += incBk;
         }
         switch(k = (K-Kb))
         {
         case 1:
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            break;
         case 2:
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rC0_0 += rA0 * rB0;
            break;
         case 3:
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rC0_0 += rA0 * rB0;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rC0_0 += rA0 * rB0;
            break;
         case 4:
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rC0_0 += rA0 * rB0;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rC0_0 += rA0 * rB0;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rC0_0 += rA0 * rB0;
            break;
         case 5:
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rC0_0 += rA0 * rB0;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rC0_0 += rA0 * rB0;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rC0_0 += rA0 * rB0;
            rA0 = pA0[4];
            rB0 = pB0[4];
            rC0_0 += rA0 * rB0;
            break;
         case 0: ;
         }
         *pC0 = rC0_0;
         pC0 += incCm;
         pA0 += incAm;
         pB0 += incBm;
      }
      while(pA0 != stM);
      pC0 += incCn;
      pA0 += incAn;
      pB0 += incBn;
   }
   while(pB0 != stN);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
void ATL_sJIK0x0x0TN0x0x0_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=0, 
 * lda=0, ldb=0, ldc=0, mu=10, nu=1, ku=6, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.2)
 */
{
   const int Mb = (M/10)*10;
   #define Nb N
   const int Kb = (K/6)*6;
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (lda*Mb);
   const float *stN = B + (ldb*Nb);
   #define incAk 6
   const int incAm = ((((lda) << 3)+((lda) << 1)) - Kb), incAn = -(Mb*lda);
   #define incBk 6
   const int incBm = -(Kb), incBn = (ldb);
   #define incCm 10
   const int incCn = (ldc) - (Mb);
   float *pC0=C;
   const float *pA0=A, *pA1=pA0+(lda), *pA2=pA1+(lda), *pA3=pA2+(lda), *pA4=pA3+(lda), *pA5=pA4+(lda), *pA6=pA5+(lda), *pA7=pA6+(lda), *pA8=pA7+(lda), *pA9=pA8+(lda);
   const float *pB0=B;
   register int k;
   register float rA0, rA1, rA2, rA3, rA4, rA5, rA6, rA7, rA8, rA9;
   register float rB0;
   register float rC0_0, rC1_0, rC2_0, rC3_0, rC4_0, rC5_0, rC6_0, rC7_0, rC8_0, rC9_0;
   if (pA0 != stM)
   {
      do /* N-loop */
      {
         do /* M-loop */
         {
            rA0 = beta;
            rC0_0 = *pC0;
            rC0_0 *= rA0;
            rC1_0 = pC0[1];
            rC1_0 *= rA0;
            rC2_0 = pC0[2];
            rC2_0 *= rA0;
            rC3_0 = pC0[3];
            rC3_0 *= rA0;
            rC4_0 = pC0[4];
            rC4_0 *= rA0;
            rC5_0 = pC0[5];
            rC5_0 *= rA0;
            rC6_0 = pC0[6];
            rC6_0 *= rA0;
            rC7_0 = pC0[7];
            rC7_0 *= rA0;
            rC8_0 = pC0[8];
            rC8_0 *= rA0;
            rC9_0 = pC0[9];
            rC9_0 *= rA0;
            for (k=0; k < Kb; k += 6) /* easy loop to unroll */
            {
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               rA2 = *pA2;
               rC0_0 += rA0 * rB0;
               rA3 = *pA3;
               rC1_0 += rA1 * rB0;
               rA4 = *pA4;
               rC2_0 += rA2 * rB0;
               rA5 = *pA5;
               rC3_0 += rA3 * rB0;
               rA6 = *pA6;
               rC4_0 += rA4 * rB0;
               rA7 = *pA7;
               rC5_0 += rA5 * rB0;
               rA8 = *pA8;
               rC6_0 += rA6 * rB0;
               rA9 = *pA9;
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[1];
               rB0 = pB0[1];
               rA1 = pA1[1];
               rA2 = pA2[1];
               rC0_0 += rA0 * rB0;
               rA3 = pA3[1];
               rC1_0 += rA1 * rB0;
               rA4 = pA4[1];
               rC2_0 += rA2 * rB0;
               rA5 = pA5[1];
               rC3_0 += rA3 * rB0;
               rA6 = pA6[1];
               rC4_0 += rA4 * rB0;
               rA7 = pA7[1];
               rC5_0 += rA5 * rB0;
               rA8 = pA8[1];
               rC6_0 += rA6 * rB0;
               rA9 = pA9[1];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[2];
               rB0 = pB0[2];
               rA1 = pA1[2];
               rA2 = pA2[2];
               rC0_0 += rA0 * rB0;
               rA3 = pA3[2];
               rC1_0 += rA1 * rB0;
               rA4 = pA4[2];
               rC2_0 += rA2 * rB0;
               rA5 = pA5[2];
               rC3_0 += rA3 * rB0;
               rA6 = pA6[2];
               rC4_0 += rA4 * rB0;
               rA7 = pA7[2];
               rC5_0 += rA5 * rB0;
               rA8 = pA8[2];
               rC6_0 += rA6 * rB0;
               rA9 = pA9[2];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[3];
               rB0 = pB0[3];
               rA1 = pA1[3];
               rA2 = pA2[3];
               rC0_0 += rA0 * rB0;
               rA3 = pA3[3];
               rC1_0 += rA1 * rB0;
               rA4 = pA4[3];
               rC2_0 += rA2 * rB0;
               rA5 = pA5[3];
               rC3_0 += rA3 * rB0;
               rA6 = pA6[3];
               rC4_0 += rA4 * rB0;
               rA7 = pA7[3];
               rC5_0 += rA5 * rB0;
               rA8 = pA8[3];
               rC6_0 += rA6 * rB0;
               rA9 = pA9[3];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[4];
               rB0 = pB0[4];
               rA1 = pA1[4];
               rA2 = pA2[4];
               rC0_0 += rA0 * rB0;
               rA3 = pA3[4];
               rC1_0 += rA1 * rB0;
               rA4 = pA4[4];
               rC2_0 += rA2 * rB0;
               rA5 = pA5[4];
               rC3_0 += rA3 * rB0;
               rA6 = pA6[4];
               rC4_0 += rA4 * rB0;
               rA7 = pA7[4];
               rC5_0 += rA5 * rB0;
               rA8 = pA8[4];
               rC6_0 += rA6 * rB0;
               rA9 = pA9[4];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[5];
               rB0 = pB0[5];
               rA1 = pA1[5];
               rA2 = pA2[5];
               rC0_0 += rA0 * rB0;
               rA3 = pA3[5];
               rC1_0 += rA1 * rB0;
               rA4 = pA4[5];
               rC2_0 += rA2 * rB0;
               rA5 = pA5[5];
               rC3_0 += rA3 * rB0;
               rA6 = pA6[5];
               rC4_0 += rA4 * rB0;
               rA7 = pA7[5];
               rC5_0 += rA5 * rB0;
               rA8 = pA8[5];
               rC6_0 += rA6 * rB0;
               rA9 = pA9[5];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               pA0 += incAk;
               pA1 += incAk;
               pA2 += incAk;
               pA3 += incAk;
               pA4 += incAk;
               pA5 += incAk;
               pA6 += incAk;
               pA7 += incAk;
               pA8 += incAk;
               pA9 += incAk;
               pB0 += incBk;
            }
            switch(k = (K-Kb))
            {
            case 1:
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               rA2 = *pA2;
               rC0_0 += rA0 * rB0;
               rA3 = *pA3;
               rC1_0 += rA1 * rB0;
               rA4 = *pA4;
               rC2_0 += rA2 * rB0;
               rA5 = *pA5;
               rC3_0 += rA3 * rB0;
               rA6 = *pA6;
               rC4_0 += rA4 * rB0;
               rA7 = *pA7;
               rC5_0 += rA5 * rB0;
               rA8 = *pA8;
               rC6_0 += rA6 * rB0;
               rA9 = *pA9;
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               break;
            case 2:
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               rA2 = *pA2;
               rC0_0 += rA0 * rB0;
               rA3 = *pA3;
               rC1_0 += rA1 * rB0;
               rA4 = *pA4;
               rC2_0 += rA2 * rB0;
               rA5 = *pA5;
               rC3_0 += rA3 * rB0;
               rA6 = *pA6;
               rC4_0 += rA4 * rB0;
               rA7 = *pA7;
               rC5_0 += rA5 * rB0;
               rA8 = *pA8;
               rC6_0 += rA6 * rB0;
               rA9 = *pA9;
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[1];
               rB0 = pB0[1];
               rA1 = pA1[1];
               rA2 = pA2[1];
               rC0_0 += rA0 * rB0;
               rA3 = pA3[1];
               rC1_0 += rA1 * rB0;
               rA4 = pA4[1];
               rC2_0 += rA2 * rB0;
               rA5 = pA5[1];
               rC3_0 += rA3 * rB0;
               rA6 = pA6[1];
               rC4_0 += rA4 * rB0;
               rA7 = pA7[1];
               rC5_0 += rA5 * rB0;
               rA8 = pA8[1];
               rC6_0 += rA6 * rB0;
               rA9 = pA9[1];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               break;
            case 3:
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               rA2 = *pA2;
               rC0_0 += rA0 * rB0;
               rA3 = *pA3;
               rC1_0 += rA1 * rB0;
               rA4 = *pA4;
               rC2_0 += rA2 * rB0;
               rA5 = *pA5;
               rC3_0 += rA3 * rB0;
               rA6 = *pA6;
               rC4_0 += rA4 * rB0;
               rA7 = *pA7;
               rC5_0 += rA5 * rB0;
               rA8 = *pA8;
               rC6_0 += rA6 * rB0;
               rA9 = *pA9;
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[1];
               rB0 = pB0[1];
               rA1 = pA1[1];
               rA2 = pA2[1];
               rC0_0 += rA0 * rB0;
               rA3 = pA3[1];
               rC1_0 += rA1 * rB0;
               rA4 = pA4[1];
               rC2_0 += rA2 * rB0;
               rA5 = pA5[1];
               rC3_0 += rA3 * rB0;
               rA6 = pA6[1];
               rC4_0 += rA4 * rB0;
               rA7 = pA7[1];
               rC5_0 += rA5 * rB0;
               rA8 = pA8[1];
               rC6_0 += rA6 * rB0;
               rA9 = pA9[1];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[2];
               rB0 = pB0[2];
               rA1 = pA1[2];
               rA2 = pA2[2];
               rC0_0 += rA0 * rB0;
               rA3 = pA3[2];
               rC1_0 += rA1 * rB0;
               rA4 = pA4[2];
               rC2_0 += rA2 * rB0;
               rA5 = pA5[2];
               rC3_0 += rA3 * rB0;
               rA6 = pA6[2];
               rC4_0 += rA4 * rB0;
               rA7 = pA7[2];
               rC5_0 += rA5 * rB0;
               rA8 = pA8[2];
               rC6_0 += rA6 * rB0;
               rA9 = pA9[2];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               break;
            case 4:
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               rA2 = *pA2;
               rC0_0 += rA0 * rB0;
               rA3 = *pA3;
               rC1_0 += rA1 * rB0;
               rA4 = *pA4;
               rC2_0 += rA2 * rB0;
               rA5 = *pA5;
               rC3_0 += rA3 * rB0;
               rA6 = *pA6;
               rC4_0 += rA4 * rB0;
               rA7 = *pA7;
               rC5_0 += rA5 * rB0;
               rA8 = *pA8;
               rC6_0 += rA6 * rB0;
               rA9 = *pA9;
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[1];
               rB0 = pB0[1];
               rA1 = pA1[1];
               rA2 = pA2[1];
               rC0_0 += rA0 * rB0;
               rA3 = pA3[1];
               rC1_0 += rA1 * rB0;
               rA4 = pA4[1];
               rC2_0 += rA2 * rB0;
               rA5 = pA5[1];
               rC3_0 += rA3 * rB0;
               rA6 = pA6[1];
               rC4_0 += rA4 * rB0;
               rA7 = pA7[1];
               rC5_0 += rA5 * rB0;
               rA8 = pA8[1];
               rC6_0 += rA6 * rB0;
               rA9 = pA9[1];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[2];
               rB0 = pB0[2];
               rA1 = pA1[2];
               rA2 = pA2[2];
               rC0_0 += rA0 * rB0;
               rA3 = pA3[2];
               rC1_0 += rA1 * rB0;
               rA4 = pA4[2];
               rC2_0 += rA2 * rB0;
               rA5 = pA5[2];
               rC3_0 += rA3 * rB0;
               rA6 = pA6[2];
               rC4_0 += rA4 * rB0;
               rA7 = pA7[2];
               rC5_0 += rA5 * rB0;
               rA8 = pA8[2];
               rC6_0 += rA6 * rB0;
               rA9 = pA9[2];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[3];
               rB0 = pB0[3];
               rA1 = pA1[3];
               rA2 = pA2[3];
               rC0_0 += rA0 * rB0;
               rA3 = pA3[3];
               rC1_0 += rA1 * rB0;
               rA4 = pA4[3];
               rC2_0 += rA2 * rB0;
               rA5 = pA5[3];
               rC3_0 += rA3 * rB0;
               rA6 = pA6[3];
               rC4_0 += rA4 * rB0;
               rA7 = pA7[3];
               rC5_0 += rA5 * rB0;
               rA8 = pA8[3];
               rC6_0 += rA6 * rB0;
               rA9 = pA9[3];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               break;
            case 5:
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               rA2 = *pA2;
               rC0_0 += rA0 * rB0;
               rA3 = *pA3;
               rC1_0 += rA1 * rB0;
               rA4 = *pA4;
               rC2_0 += rA2 * rB0;
               rA5 = *pA5;
               rC3_0 += rA3 * rB0;
               rA6 = *pA6;
               rC4_0 += rA4 * rB0;
               rA7 = *pA7;
               rC5_0 += rA5 * rB0;
               rA8 = *pA8;
               rC6_0 += rA6 * rB0;
               rA9 = *pA9;
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[1];
               rB0 = pB0[1];
               rA1 = pA1[1];
               rA2 = pA2[1];
               rC0_0 += rA0 * rB0;
               rA3 = pA3[1];
               rC1_0 += rA1 * rB0;
               rA4 = pA4[1];
               rC2_0 += rA2 * rB0;
               rA5 = pA5[1];
               rC3_0 += rA3 * rB0;
               rA6 = pA6[1];
               rC4_0 += rA4 * rB0;
               rA7 = pA7[1];
               rC5_0 += rA5 * rB0;
               rA8 = pA8[1];
               rC6_0 += rA6 * rB0;
               rA9 = pA9[1];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[2];
               rB0 = pB0[2];
               rA1 = pA1[2];
               rA2 = pA2[2];
               rC0_0 += rA0 * rB0;
               rA3 = pA3[2];
               rC1_0 += rA1 * rB0;
               rA4 = pA4[2];
               rC2_0 += rA2 * rB0;
               rA5 = pA5[2];
               rC3_0 += rA3 * rB0;
               rA6 = pA6[2];
               rC4_0 += rA4 * rB0;
               rA7 = pA7[2];
               rC5_0 += rA5 * rB0;
               rA8 = pA8[2];
               rC6_0 += rA6 * rB0;
               rA9 = pA9[2];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[3];
               rB0 = pB0[3];
               rA1 = pA1[3];
               rA2 = pA2[3];
               rC0_0 += rA0 * rB0;
               rA3 = pA3[3];
               rC1_0 += rA1 * rB0;
               rA4 = pA4[3];
               rC2_0 += rA2 * rB0;
               rA5 = pA5[3];
               rC3_0 += rA3 * rB0;
               rA6 = pA6[3];
               rC4_0 += rA4 * rB0;
               rA7 = pA7[3];
               rC5_0 += rA5 * rB0;
               rA8 = pA8[3];
               rC6_0 += rA6 * rB0;
               rA9 = pA9[3];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[4];
               rB0 = pB0[4];
               rA1 = pA1[4];
               rA2 = pA2[4];
               rC0_0 += rA0 * rB0;
               rA3 = pA3[4];
               rC1_0 += rA1 * rB0;
               rA4 = pA4[4];
               rC2_0 += rA2 * rB0;
               rA5 = pA5[4];
               rC3_0 += rA3 * rB0;
               rA6 = pA6[4];
               rC4_0 += rA4 * rB0;
               rA7 = pA7[4];
               rC5_0 += rA5 * rB0;
               rA8 = pA8[4];
               rC6_0 += rA6 * rB0;
               rA9 = pA9[4];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               break;
            case 0: ;
            }
            *pC0 = rC0_0;
            pC0[1] = rC1_0;
            pC0[2] = rC2_0;
            pC0[3] = rC3_0;
            pC0[4] = rC4_0;
            pC0[5] = rC5_0;
            pC0[6] = rC6_0;
            pC0[7] = rC7_0;
            pC0[8] = rC8_0;
            pC0[9] = rC9_0;
            pC0 += incCm;
            pA0 += incAm;
            pA1 += incAm;
            pA2 += incAm;
            pA3 += incAm;
            pA4 += incAm;
            pA5 += incAm;
            pA6 += incAm;
            pA7 += incAm;
            pA8 += incAm;
            pA9 += incAm;
            pB0 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pA0 += incAn;
         pA1 += incAn;
         pA2 += incAn;
         pA3 += incAn;
         pA4 += incAn;
         pA5 += incAn;
         pA6 += incAn;
         pA7 += incAn;
         pA8 += incAn;
         pA9 += incAn;
         pB0 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=M-Mb)
      ATL_sJIK0x0x0TN1x1x6_a1_bX(k, N, K, alpha, ca + (Mb*lda), lda, cb, ldb, beta, cc + (Mb), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
