#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
static void ATL_sJIK0x0x78TN1x1x6_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=78, 
 * lda=78, ldb=78, ldc=0, mu=1, nu=1, ku=6, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.2)
 */
{
   #define Mb M
   #define Nb N
   const float *stM = A + (78*(Mb));
   const float *stN = B + (78*(Nb));
   #define incAk 6
   const int incAm = 0, incAn = -(78*(Mb));
   #define incBk 6
   const int incBm = -78, incBn = 78;
   #define incCm 1
   const int incCn = (ldc) - (Mb);
   float *pC0=C;
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0;
   register float rB0;
   register float rC0_0;
   do /* N-loop */
   {
      do /* M-loop */
      {
         rA0 = beta;
         rC0_0 = *pC0;
         rC0_0 *= rA0;
         for (k=0; k < 13; k++) /* easy loop to unroll */
         {
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rC0_0 += rA0 * rB0;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rC0_0 += rA0 * rB0;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rC0_0 += rA0 * rB0;
            rA0 = pA0[4];
            rB0 = pB0[4];
            rC0_0 += rA0 * rB0;
            rA0 = pA0[5];
            rB0 = pB0[5];
            rC0_0 += rA0 * rB0;
            pA0 += incAk;
            pB0 += incBk;
         }
         *pC0 = rC0_0;
         pC0 += incCm;
         pA0 += incAm;
         pB0 += incBm;
      }
      while(pA0 != stM);
      pC0 += incCn;
      pA0 += incAn;
      pB0 += incBn;
   }
   while(pB0 != stN);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
void ATL_sJIK0x0x78TN78x78x0_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=78, 
 * lda=78, ldb=78, ldc=0, mu=10, nu=1, ku=6, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.2)
 */
{
   const int Mb = (M/10)*10;
   #define Nb N
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (78*(Mb));
   const float *stN = B + (78*(Nb));
   #define incAk 6
   const int incAm = 702, incAn = -(78*(Mb));
   #define incBk 6
   const int incBm = -78, incBn = 78;
   #define incCm 10
   const int incCn = (ldc) - (Mb);
   float *pC0=C;
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0, rA1, rA2, rA3, rA4, rA5, rA6, rA7, rA8, rA9;
   register float rB0;
   register float rC0_0, rC1_0, rC2_0, rC3_0, rC4_0, rC5_0, rC6_0, rC7_0, rC8_0, rC9_0;
   if (pA0 != stM)
   {
      do /* N-loop */
      {
         do /* M-loop */
         {
            rA0 = beta;
            rC0_0 = *pC0;
            rC0_0 *= rA0;
            rC1_0 = pC0[1];
            rC1_0 *= rA0;
            rC2_0 = pC0[2];
            rC2_0 *= rA0;
            rC3_0 = pC0[3];
            rC3_0 *= rA0;
            rC4_0 = pC0[4];
            rC4_0 *= rA0;
            rC5_0 = pC0[5];
            rC5_0 *= rA0;
            rC6_0 = pC0[6];
            rC6_0 *= rA0;
            rC7_0 = pC0[7];
            rC7_0 *= rA0;
            rC8_0 = pC0[8];
            rC8_0 *= rA0;
            rC9_0 = pC0[9];
            rC9_0 *= rA0;
            for (k=0; k < 13; k++) /* easy loop to unroll */
            {
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = pA0[78];
               rA2 = pA0[156];
               rC0_0 += rA0 * rB0;
               rA3 = pA0[234];
               rC1_0 += rA1 * rB0;
               rA4 = pA0[312];
               rC2_0 += rA2 * rB0;
               rA5 = pA0[390];
               rC3_0 += rA3 * rB0;
               rA6 = pA0[468];
               rC4_0 += rA4 * rB0;
               rA7 = pA0[546];
               rC5_0 += rA5 * rB0;
               rA8 = pA0[624];
               rC6_0 += rA6 * rB0;
               rA9 = pA0[702];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[1];
               rB0 = pB0[1];
               rA1 = pA0[79];
               rA2 = pA0[157];
               rC0_0 += rA0 * rB0;
               rA3 = pA0[235];
               rC1_0 += rA1 * rB0;
               rA4 = pA0[313];
               rC2_0 += rA2 * rB0;
               rA5 = pA0[391];
               rC3_0 += rA3 * rB0;
               rA6 = pA0[469];
               rC4_0 += rA4 * rB0;
               rA7 = pA0[547];
               rC5_0 += rA5 * rB0;
               rA8 = pA0[625];
               rC6_0 += rA6 * rB0;
               rA9 = pA0[703];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[2];
               rB0 = pB0[2];
               rA1 = pA0[80];
               rA2 = pA0[158];
               rC0_0 += rA0 * rB0;
               rA3 = pA0[236];
               rC1_0 += rA1 * rB0;
               rA4 = pA0[314];
               rC2_0 += rA2 * rB0;
               rA5 = pA0[392];
               rC3_0 += rA3 * rB0;
               rA6 = pA0[470];
               rC4_0 += rA4 * rB0;
               rA7 = pA0[548];
               rC5_0 += rA5 * rB0;
               rA8 = pA0[626];
               rC6_0 += rA6 * rB0;
               rA9 = pA0[704];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[3];
               rB0 = pB0[3];
               rA1 = pA0[81];
               rA2 = pA0[159];
               rC0_0 += rA0 * rB0;
               rA3 = pA0[237];
               rC1_0 += rA1 * rB0;
               rA4 = pA0[315];
               rC2_0 += rA2 * rB0;
               rA5 = pA0[393];
               rC3_0 += rA3 * rB0;
               rA6 = pA0[471];
               rC4_0 += rA4 * rB0;
               rA7 = pA0[549];
               rC5_0 += rA5 * rB0;
               rA8 = pA0[627];
               rC6_0 += rA6 * rB0;
               rA9 = pA0[705];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[4];
               rB0 = pB0[4];
               rA1 = pA0[82];
               rA2 = pA0[160];
               rC0_0 += rA0 * rB0;
               rA3 = pA0[238];
               rC1_0 += rA1 * rB0;
               rA4 = pA0[316];
               rC2_0 += rA2 * rB0;
               rA5 = pA0[394];
               rC3_0 += rA3 * rB0;
               rA6 = pA0[472];
               rC4_0 += rA4 * rB0;
               rA7 = pA0[550];
               rC5_0 += rA5 * rB0;
               rA8 = pA0[628];
               rC6_0 += rA6 * rB0;
               rA9 = pA0[706];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               rA0 = pA0[5];
               rB0 = pB0[5];
               rA1 = pA0[83];
               rA2 = pA0[161];
               rC0_0 += rA0 * rB0;
               rA3 = pA0[239];
               rC1_0 += rA1 * rB0;
               rA4 = pA0[317];
               rC2_0 += rA2 * rB0;
               rA5 = pA0[395];
               rC3_0 += rA3 * rB0;
               rA6 = pA0[473];
               rC4_0 += rA4 * rB0;
               rA7 = pA0[551];
               rC5_0 += rA5 * rB0;
               rA8 = pA0[629];
               rC6_0 += rA6 * rB0;
               rA9 = pA0[707];
               rC7_0 += rA7 * rB0;
               rC8_0 += rA8 * rB0;
               rC9_0 += rA9 * rB0;
               pA0 += incAk;
               pB0 += incBk;
            }
            *pC0 = rC0_0;
            pC0[1] = rC1_0;
            pC0[2] = rC2_0;
            pC0[3] = rC3_0;
            pC0[4] = rC4_0;
            pC0[5] = rC5_0;
            pC0[6] = rC6_0;
            pC0[7] = rC7_0;
            pC0[8] = rC8_0;
            pC0[9] = rC9_0;
            pC0 += incCm;
            pA0 += incAm;
            pB0 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pA0 += incAn;
         pB0 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=M-Mb)
      ATL_sJIK0x0x78TN1x1x6_a1_bX(k, N, 78, alpha, ca + (78*(Mb)), lda, cb, ldb, beta, cc + (Mb), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
